project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Biases in U.S. Elections Data"
  author:
    - Marek Kampa (mk4300)
    - Jingyang Wang (jw4656)
  repo-url: https://github.com/Karmpje/uninformed_elections
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


